#!/usr/bin/env node
/**
 * Codegen: single-source CORE_VERSION from package.json into src/generated/version.ts.
 * Runs before tsc (build + lint). The generated file is gitignored — the package
 * version has exactly one source of truth (package.json), never a hand-kept constant.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf-8"));

const out = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit, do not commit.
export const CORE_VERSION = ${JSON.stringify(pkg.version)};
`;

mkdirSync(join(root, "src", "generated"), { recursive: true });
writeFileSync(join(root, "src", "generated", "version.ts"), out, "utf-8");
