/**
 * Live-sync (F5 — plan/05-interop).
 *
 * When a persona evolves, the host's adopted subagent must see it. A full
 * qualitative recompile of PERSONA.md / .claude/agents/<slug>.md is LLM-bound, but
 * the *runtime state* can be synced deterministically and immediately:
 *
 *   - upsert a delimited LIVE-STATE block into the compiled doc (current envelope
 *     values, mood, last mutation, sigil seed) so a host re-reading the file sees
 *     the persona's current condition;
 *   - write a .live.json notify marker (state hash + counts + ts) a host watcher
 *     can poll to know "the persona changed".
 *
 * This is the loop's `recompile` hook. The qualitative recompile remains a separate,
 * provider-backed step; nothing here invents prose.
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { readState, type PersonaHandle, type StateFile } from "./persona.js";
import { sigilParams } from "./sigil.js";

export const LIVE_START = "<!-- PERSONAXIS:LIVE-STATE start -->";
export const LIVE_END = "<!-- PERSONAXIS:LIVE-STATE end -->";

export function renderLiveBlock(handle: PersonaHandle, state: StateFile): string {
  const last = state.mutation_log.at(-1);
  const lines = [
    LIVE_START,
    `<!-- generated by personaxis live-sync; do not edit by hand -->`,
    `> **Live state** (sigil #${sigilParams(handle.frontmatter).seed.toString(16)}) — updated ${new Date().toISOString()}`,
    ">",
    "> | field | value |",
    "> |---|---|",
    ...Object.entries(state.values).map(([k, v]) => `> | ${k} | ${v.toFixed(3)} |`),
    ">",
    `> mutations: ${state.mutation_log.length}` +
      (last ? ` · last: ${last.field} → ${last.to.toFixed(3)} (${last.reason})` : ""),
    LIVE_END,
  ];
  return lines.join("\n");
}

/** Replace an existing LIVE-STATE block, or append one. */
export function upsertLiveBlock(doc: string, block: string): string {
  const start = doc.indexOf(LIVE_START);
  const end = doc.indexOf(LIVE_END);
  if (start !== -1 && end !== -1 && end > start) {
    return doc.slice(0, start) + block + doc.slice(end + LIVE_END.length);
  }
  const sep = doc.endsWith("\n") ? "\n" : "\n\n";
  return doc + sep + block + "\n";
}

export interface LiveMarker {
  ts: string;
  state_hash: string;
  mutations: number;
  values: Record<string, number>;
}

function markerPath(personaPath: string): string {
  return join(dirname(personaPath), ".live.json");
}

export function stateHash(state: StateFile): string {
  return createHash("sha256").update(JSON.stringify(state.values)).digest("hex").slice(0, 16);
}

/** Write the notify marker beside the persona; returns it. */
export function writeLiveMarker(personaPath: string, state: StateFile): LiveMarker {
  const marker: LiveMarker = {
    ts: new Date().toISOString(),
    state_hash: stateHash(state),
    mutations: state.mutation_log.length,
    values: state.values,
  };
  writeFileSync(markerPath(personaPath), JSON.stringify(marker, null, 2) + "\n", "utf-8");
  return marker;
}

/** Sync the compiled doc's live block (if the file exists) + write the marker. */
export function liveSync(handle: PersonaHandle, compiledPath: string | undefined, state: StateFile): LiveMarker {
  if (compiledPath && existsSync(compiledPath)) {
    const doc = readFileSync(compiledPath, "utf-8");
    writeFileSync(compiledPath, upsertLiveBlock(doc, renderLiveBlock(handle, state)), "utf-8");
  }
  return writeLiveMarker(handle.personaPath, state);
}

/**
 * Build a `recompile` hook for the LivingLoop: on drift it syncs the live state
 * block into `compiledPath` (the host's adopted doc) and writes the notify marker.
 */
export function makeRecompileHook(
  compiledPath?: string,
): (handle: PersonaHandle) => Promise<void> {
  return async (handle: PersonaHandle) => {
    const state = readState(handle.statePath);
    liveSync(handle, compiledPath, state);
  };
}
