/**
 * Structural self-awareness for a persona (F2, expanded V5.P0.1, rebuilt on the work map in E79).
 *
 * A persona must know, at runtime, WHO it is, WHERE it sits and WHAT it has: which spec defines it and
 * under which spec_version it operates, whether it is the project MAIN persona or a SUB-persona, what
 * each thing it has is for, and where its work goes. This block is injected into the agent's system
 * prompt every turn, it is NOT baked into the compiled PERSONA.md (which stays portable + purely
 * qualitative) and is NEVER written into personaxis.md.
 *
 * ## What changed in E79, and why
 *
 * The block used to list the persona's folders and the files inside them. It never said what any of
 * them was for, named no services, and said nothing about where a deliverable goes, so a persona had
 * to open files to learn whether they mattered. What it has now comes from the engine's work map
 * (`core/src/run/work-map.ts`), which every surface can build.
 *
 * Two things left the block on purpose. The sandbox posture, because it changes when somebody presses
 * shift+tab and this block sits in the cached prefix: the posture already travels in its own message
 * each turn (`agent.ts`, E20). And the session list, which named every conversation file, so the
 * prefix changed between the first turn of a session and the second.
 */

import { dirname, relative, resolve } from "node:path";

import { run } from "@personaxis/core";

import { compiledPathFor, isSubagentPath, slugAddressFromPath } from "../load.js";

export interface AwarenessOpts {
  /** Persona frontmatter (spec_version, apiVersion, improvement_policy, identity). */
  frontmatter?: Record<string, unknown>;
  /** Model id answering this session (informational). */
  model?: string;
  /** Working directory of the session (project root). */
  cwd?: string;
  /** The standing objective set with /goal, rendered in the recency slot (V7.A7). */
  goal?: string;
}

function fmString(fm: Record<string, unknown> | undefined, path: string[]): string | undefined {
  let cur: unknown = fm;
  for (const key of path) {
    if (!cur || typeof cur !== "object") return undefined;
    cur = (cur as Record<string, unknown>)[key];
  }
  return typeof cur === "string" ? cur : undefined;
}

/** Build the `# Runtime context` block for the persona at `personaPath`. */
export function buildAwarenessBlock(personaPath: string, opts: AwarenessOpts = {}): string {
  const lines: string[] = ["# Runtime context (generated each session, not part of your persona files)"];
  const fm = opts.frontmatter;
  const cwd = opts.cwd ?? process.cwd();
  const address = slugAddressFromPath(personaPath);
  const isSub = isSubagentPath(personaPath) && !!address;
  const rel = (p: string) => {
    const r = relative(cwd, resolve(p));
    return r && !r.startsWith("..") ? r.replace(/\\/g, "/") : resolve(p).replace(/\\/g, "/");
  };

  // Who I am and what defines me.
  const displayName = fmString(fm, ["identity", "display_name"]) ?? fmString(fm, ["metadata", "name"]);
  const specVersion = fmString(fm, ["spec_version"]);
  const apiVersion = fmString(fm, ["apiVersion"]);
  lines.push("", "## Who you are here");
  lines.push(
    isSub
      ? `You are the SUB-persona \`@${address}\`${displayName ? ` ("${displayName}")` : ""}, delegated under the project's main persona. ` +
          "You are an independent persona with your own spec, state, memory and self-improvement ledger. " +
          "You may READ other personas' files but only WRITE within your own folder."
      : `You are the MAIN persona of this project${displayName ? ` ("${displayName}")` : ""} (the repo-wide agent). ` +
          "Sub-personas are specialists you can delegate to; you may READ their files but never WRITE them.",
  );
  lines.push("", "## Your defining files (the personaxis.md spec)");
  lines.push(
    `- Source of truth: \`${rel(personaPath)}\`` +
      (specVersion || apiVersion
        ? ` (spec_version ${specVersion ?? "?"}${apiVersion ? `, ${apiVersion}` : ""})`
        : "") +
      ": your quantitative 10-layer spec. You do not edit it directly; changes go through governance.",
    `- Compiled identity: \`${rel(compiledPathFor(personaPath))}\`: the prose version of the spec that hosts read. Regenerated by compile; hand-edits are folded back via decompile.`,
    `- Mutable state: \`${rel(dirname(personaPath))}/state.json\`: your live values, clamped to declared envelopes; every change lands in the mutation_log.`,
  );

  // Session facts that do not move while the session runs.
  const mode = fmString(fm, ["improvement_policy", "mode"]);
  const session: string[] = [];
  session.push(`- Project: \`${cwd.replace(/\\/g, "/")}\``);
  if (opts.model) session.push(`- Model answering this session: ${opts.model}`);
  if (mode) session.push(`- Self-improvement mode: ${mode} (your edits ${mode === "locked" ? "are blocked" : mode === "suggesting" ? "queue for human review" : "may auto-apply within governance"})`);
  lines.push("", "## This session", ...session);

  // E79: what the persona has and what each thing is for, from the engine's work map.
  lines.push("", run.renderWorkMap(run.workMapFor(personaPath, { workspaceRoot: cwd, ...(fm ? { frontmatter: fm } : {}) })));

  // V7.A7: the standing goal goes LAST, the recency slot the model attends to most.
  // It used to sit buried mid-prompt, so when asked "what is your goal" the model went
  // looking through memory tools instead of reading what it already had.
  if (opts.goal?.trim()) {
    lines.push(
      "",
      "## Your standing objective (set by the user with /goal)",
      opts.goal.trim(),
      "It stands until the user clears it. If asked what your goal is, answer from this line; do not search memory.",
    );
  }

  return lines.join("\n");
}
