#!/usr/bin/env node
/**
 * Embed the canonical JSON Schemas into a generated TS module so the package
 * works inside a single compiled binary (bun compile) AND as a plain node
 * package — no runtime fs reads. Source of truth stays schema/*.json
 * (byte-identical to the persona.md repo). Run before tsc (wired into build).
 *
 * Output: packages/spec/src/generated/schemas.ts (git-ignored, regenerated on build).
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, "..");
const read = (p) => readFileSync(resolve(pkg, p), "utf-8");

const schemas = {
  personaSchema: "schema/persona.schema.json",
  // Frozen 0.10 schema: validates 0.3.0–0.10.0 documents during the 1.x
  // read-compat window (the validator dispatches on spec_version).
  personaSchemaLegacy: "schema/legacy/persona-0.10.schema.json",
  policySchema: "schema/policy.schema.json",
  stateSchema: "schema/state.schema.json",
  memorySchema: "schema/memory.schema.json",
};

const lines = [
  "// AUTO-GENERATED by scripts/gen-schemas.mjs — do not edit by hand.",
  "/* eslint-disable */",
  "",
];
for (const [name, file] of Object.entries(schemas)) {
  const text = read(file);
  JSON.parse(text); // validate it parses before embedding
  lines.push(`export const ${name}: Record<string, unknown> = JSON.parse(${JSON.stringify(text)});`);
}
lines.push("");

const outDir = resolve(pkg, "src", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "schemas.ts"), lines.join("\n"), "utf-8");
console.log("embedded schemas -> packages/spec/src/generated/schemas.ts");
