/**
 * `inspect_self` (E119): the persona looks at itself, read-only, at the moment it needs to.
 *
 * ## Why a tool and not another line in the prompt
 *
 * Asked "what exactly can you do for me, and what do you have to work with?", a persona on the autonomy bench
 * named its three skills and never the service it delivers, 0 runs in 6 with Qwen and half with Cohere, although
 * the service was right there in its index. Four attempts to fix that by wording (the index, the identity, a
 * preference, sections) changed nothing or did harm. What has moved behaviour in this programme is data in a
 * tool's result, arriving when the persona is about to act on it (`check_page` giving the line of a fault,
 * a large file previewed as its index). So what the persona has is also something it can ASK for, and the answer
 * arrives in the step where it is answering about itself.
 *
 * ## What it returns
 *
 * The same map the index shows, generated by the same function, so the two can never disagree, and how the
 * persona is right now: the bands that differ from what its identity says. Nothing it could not already read;
 * nothing it can change from here. Changing itself is `propose_change`, behind `editGate`, and not this.
 */

import { READ_CLASS } from "./gates.js";
import type { ToolSpec } from "./registry.js";

const INSPECT_SELF_TOOL = "inspect_self";

export interface InspectSelfOptions {
	/** What the persona has, rendered: skills, services, references, memory. Read when the tool is CALLED. */
	readonly has: () => string;
	/** How it is right now, rendered; empty when nothing differs from its identity. Read when CALLED. */
	readonly now: () => string;
}

export function inspectSelfTool(options: InspectSelfOptions): ToolSpec {
	return {
		name: INSPECT_SELF_TOOL,
		category: "meta",
		description:
			"Look at yourself: the skills, the services you deliver, the references and the memory you have, and how you are right now. " +
			"Call it before you tell someone what you can do or what you have to work with.",
		parameters: { type: "object", additionalProperties: false, properties: {} },
		isReadOnly: true,
		isConcurrencySafe: true,
		// It reads what the persona already is and writes nothing.
		envelope: [],
		gate: () => ({ decision: "allow", reason: "reading what you are, which grants nothing", class: READ_CLASS }),
		execute: async () => {
			const has = options.has().trim();
			const now = options.now().trim();
			return [has || "You have no skills, services or references on this disk.", now || "How you are right now: as your identity says; nothing has moved."].join("\n\n");
		},
	};
}
