#!/usr/bin/env node
/**
 * Embed runtime assets into a generated TS module so the CLI works as a single
 * compiled binary (`bun compile`) AND as a node package — without runtime fs reads
 * of schema/template files that aren't present inside a compiled binary.
 *
 * Source of truth stays the on-disk schema/*.json + templates/* (byte-identical to
 * persona.md). This codegen just inlines them. Run before `tsc` (wired into build).
 *
 * Output: packages/cli/src/generated/assets.ts (git-ignored, regenerated on build).
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const cli = resolve(here, "..", "packages", "cli");

const read = (p) => readFileSync(resolve(cli, p), "utf-8");
const pkg = JSON.parse(read("package.json"));

// Schemas moved to @personaxis/spec (F2.9) — embedded there by its own gen script.
const templateFiles = [
  "personaxis_template.md",
  "PERSONA_template.md",
  "policy_template.yaml",
  "starter_persona.md",
];

const lines = [
  "// AUTO-GENERATED by scripts/embed-assets.mjs — do not edit by hand.",
  "// Inlines schema/template assets so the CLI runs as a single compiled binary.",
  "/* eslint-disable */",
  "",
  `export const version = ${JSON.stringify(pkg.version)};`,
  "",
];


lines.push("export const templates: Record<string, string> = {");
for (const f of templateFiles) {
  lines.push(`  ${JSON.stringify(f)}: ${JSON.stringify(read("templates/" + f))},`);
}
lines.push("};");
lines.push("");

// The normative spec doc (byte-identical to persona.md/docs/SPEC.md), so `personaxis spec` prints the
// CURRENT spec and can never go stale — it's regenerated from the single source on every build.
lines.push(`export const specDoc: string = ${JSON.stringify(read("SPEC.md"))};`);
lines.push("");

const outDir = resolve(cli, "src", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "assets.ts"), lines.join("\n"), "utf-8");
console.log("embedded assets -> packages/cli/src/generated/assets.ts");
